// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idujtvokslevjyrnmcnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkdWp0dm9rc2xldmp5cm5tY25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyODAwOTQsImV4cCI6MjA2Nzg1NjA5NH0.zVRnyFkAiDtUyoCUUM0AmM4fejfs5g01sF9PGzZv6EE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});